version: "3.9"
services:
  postgres:
    container_name: reportpipe.postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
