name: Go

on:
  workflow_dispatch: null

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Start docker compose and migrate db
        run: make db-up
      - name: All tests
        run: go test ./...
